exports.state = ['setState', 'resetState'];

exports.messenger = [
  'sendMessage',
  'sendText',
  'sendAttachment',
  'sendAudio',
  'sendImage',
  'sendVideo',
  'sendFile',
  'sendTemplate',
  'sendButtonTemplate',
  'sendGenericTemplate',
  'sendListTemplate',
  'sendOpenGraphTemplate',
  'sendMediaTemplate',
  'sendReceiptTemplate',
  'sendAirlineBoardingPassTemplate',
  'sendAirlineCheckinTemplate',
  'sendAirlineItineraryTemplate',
  'sendAirlineFlightUpdateTemplate',
  'sendSenderAction',
  'markSeen',
  'typingOn',
  'typingOff',
  'associateLabel',
  'dissociateLabel',
  'getAssociatedLabels',
];

exports.line = [
  'sendText',
  'sendImage',
  'sendVideo',
  'sendAudio',
  'sendLocation',
  'sendSticker',
  'sendImagemap',
  'sendButtonTemplate',
  'sendConfirmTemplate',
  'sendCarouselTemplate',
  'sendImageCarouselTemplate',
  'reply',
  'replyText',
  'replyImage',
  'replyVideo',
  'replyAudio',
  'replyLocation',
  'replySticker',
  'replyImagemap',
  'replyButtonTemplate',
  'replyConfirmTemplate',
  'replyCarouselTemplate',
  'replyImageCarouselTemplate',
  'sendImageCarouselTemplate',
  'push',
  'pushText',
  'pushImage',
  'pushVideo',
  'pushAudio',
  'pushLocation',
  'pushSticker',
  'pushImagemap',
  'pushButtonTemplate',
  'pushConfirmTemplate',
  'pushCarouselTemplate',
  'pushImageCarouselTemplate',
  'getLinkedRichMenu',
  'linkRichMenu',
  'unlinkRichMenu',
];

exports.slack = ['sendText', 'postMessage'];

exports.telegram = [
  'sendText',
  'sendMessage',
  'sendPhoto',
  'sendAudio',
  'sendDocument',
  'sendSticker',
  'sendVideo',
  'sendVoice',
  'sendVideoNote',
  'sendLocation',
  'sendVenue',
  'sendContact',
  'sendChatAction',
];

exports.viber = [
  'sendMessage',
  'sendText',
  'sendPicture',
  'sendVideo',
  'sendFile',
  'sendContact',
  'sendLocation',
  'sendURL',
  'sendSticker',
  'sendCarouselContent',
];
