exports.common = ['setState', 'resetState', 'typing'];

exports.messenger = [
  'sendMessage',
  'sendText',
  'sendAttachment',
  'sendAudio',
  'sendImage',
  'sendVideo',
  'sendFile',
  'sendTemplate',
  'sendButtonTemplate',
  'sendGenericTemplate',
  'sendListTemplate',
  'sendOpenGraphTemplate',
  'sendMediaTemplate',
  'sendReceiptTemplate',
  'sendAirlineBoardingPassTemplate',
  'sendAirlineCheckinTemplate',
  'sendAirlineItineraryTemplate',
  'sendAirlineFlightUpdateTemplate',
  'sendSenderAction',
  'markSeen',
  'typingOn',
  'typingOff',
  'passThreadControl',
  'passThreadControlToPageInbox',
  'takeThreadControl',
  'requestThreadControl',
  'associateLabel',
  'dissociateLabel',
];

exports.line = [
  'sendText',
  'sendImage',
  'sendVideo',
  'sendAudio',
  'sendLocation',
  'sendSticker',
  'sendImagemap',
  'sendButtonTemplate',
  'sendConfirmTemplate',
  'sendCarouselTemplate',
  'sendImageCarouselTemplate',
  'reply',
  'replyText',
  'replyImage',
  'replyVideo',
  'replyAudio',
  'replyLocation',
  'replySticker',
  'replyImagemap',
  'replyButtonTemplate',
  'replyConfirmTemplate',
  'replyCarouselTemplate',
  'replyImageCarouselTemplate',
  'sendImageCarouselTemplate',
  'push',
  'pushText',
  'pushImage',
  'pushVideo',
  'pushAudio',
  'pushLocation',
  'pushSticker',
  'pushImagemap',
  'pushButtonTemplate',
  'pushConfirmTemplate',
  'pushCarouselTemplate',
  'pushImageCarouselTemplate',
  'linkRichMenu',
  'unlinkRichMenu',
];

exports.slack = ['sendText', 'postMessage', 'postEphemeral'];

exports.telegram = [
  'sendText',
  'sendMessage',
  'sendPhoto',
  'sendAudio',
  'sendDocument',
  'sendSticker',
  'sendVideo',
  'sendVoice',
  'sendVideoNote',
  'sendMediaGroup',
  'sendLocation',
  'sendVenue',
  'sendContact',
  'sendChatAction',
  'editMessageText',
  'editMessageCaption',
  'editMessageReplyMarkup',
  'deleteMessage',
  'editMessageLiveLocation',
  'stopMessageLiveLocation',
  'forwardMessageFrom',
  'forwardMessageTo',
  'kickChatMember',
  'unbanChatMember',
  'restrictChatMember',
  'promoteChatMember',
  'exportChatInviteLink',
  'setChatPhoto',
  'deleteChatPhoto',
  'setChatTitle',
  'setChatDescription',
  'setChatStickerSet',
  'deleteChatStickerSet',
  'pinChatMessage',
  'unpinChatMessage',
  'leaveChat',
  'sendInvoice',
  'answerShippingQuery',
  'answerPreCheckoutQuery',
  'answerInlineQuery',
  'sendGame',
  'setGameScore',
];

exports.viber = [
  'sendMessage',
  'sendText',
  'sendPicture',
  'sendVideo',
  'sendFile',
  'sendContact',
  'sendLocation',
  'sendURL',
  'sendSticker',
  'sendCarouselContent',
];

exports.fb = ['sendComment', 'sendPrivateReply'];
